/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import java.util.Calendar;

/**
 *
 * @author admin
 */
public class YearChooserPanel extends javax.swing.JPanel {

    private int selectedYear;

    /**
     * Creates new form YearChooserPanel
     */
    public YearChooserPanel() {
        initComponents();
//        yearComboBox.setSelectedItem();
        int currentYear = Calendar.getInstance().get(Calendar.YEAR);
        int yearstart = 2000;

        for (int i = currentYear; i >=yearstart; i--) {
            yearComboBox.addItem(String.valueOf(i));
        }
        yearComboBox.setSelectedItem(String.valueOf(currentYear));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yearComboBox = new javax.swing.JComboBox<>();

        yearComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yearComboBox.setSelectedItem(Calendar.getInstance().get(Calendar.YEAR));
        yearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(yearComboBox, 0, 175, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(yearComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void yearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboBoxActionPerformed
        selectedYear = Integer.parseInt(yearComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_yearComboBoxActionPerformed
    public int getSelectedYear() {
        return selectedYear;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> yearComboBox;
    // End of variables declaration//GEN-END:variables
}
